service: Python-Flask-App
provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  memorySize: 1024
  timeout: 300
  versionFunctions: true
  role: !GetAtt LambdaRole.Arn

resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Lambda_Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: getList
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                  Resource:
                    - arn:aws:s3:::<BUCKET>
                - Effect: Allow
package:
  artifact: pythonscript.zip
functions:
    name: Prowler
    handler: lambda_function.lambda_handler
    environment:
      REGION: eu-west-1
